# Arreglos y Clases
## Matrices

In [3]:
# Estamos creando una lista de listas

A = [[1,2,3],[4,5,6],[7,8,9]]
print(A)
type(A)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [6]:
# Vamos a crear otra lista de listas

B = [[21, 34, 40], [71, 17, 77], [73, 81, 28]]

A + B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]

[[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]]

In [10]:
A[0][0]

# La primer posición para buscar es cero, no uno

1

## Vectores y Listas

In [14]:
L = A[0]
M = B[0]
L + M

a = L[0]
b = M[0]
a+b

22

In [15]:
a==1

True

## Suma de "vectores"

In [16]:
len(L)==len(M)

True

In [18]:
suma = [L[0]+M[0], L[1]+M[1], L[2]+M[2]]
print(suma)

[22, 36, 43]


In [20]:
suma = [L[i]+M[i] for i in range(3)]
print(suma)

[22, 36, 43]


## Creación de Funciones Globales

  La función para crear funciones es `def`que se cierra con un debug (`print` o `return`)

In [21]:
def Hola():
  print("Hola yo soy Mateo")

In [22]:
Hola()

Hola yo soy Mateo


In [2]:
def saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")


In [3]:
saludar("Mateo",18)

Hola, me llamo Mateo y tengo 18 años


In [9]:
def par(x):
  for x in range(10):
    if x%2==0:
      print(f"{x} es un número par")
    else:
      print(f"{x} es un número impar")

In [10]:
par(5)

0 es un número par
1 es un número impar
2 es un número par
3 es un número impar
4 es un número par
5 es un número impar
6 es un número par
7 es un número impar
8 es un número par
9 es un número impar


In [11]:
def suma_vectorial(L,M):
  x = [L[i]+M[i] for i in range(0,len(L))]
  return x

In [12]:
L = [1,2,3]
M = [21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

## Módulos o librerías

In [13]:
import math
from math import sqrt, pi

In [14]:
sqrt(7)

2.6457513110645907

In [15]:
pi

3.141592653589793

# Módulo NumPy

In [19]:
import numpy as np
L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [21]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)
print(C_matriz)
print(A_matriz)


[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [22]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])